services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ingestion_db
    ports:
      - "${HOST_PORT_DB:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ingestion_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mock-api:
    build:
      context: ./mock_api
    ports:
      - "${HOST_PORT_MOCK_API:-8001}:8000" # Host Port -> Container 8000
    environment:
      - PYTHONUNBUFFERED=1

  ingestion-service:
    build:
      context: ./ingestion_service
    ports:
      - "${HOST_PORT_INGESTOR:-8000}:8000" # Host Port -> Container 8000
    depends_on:
      postgres:
        condition: service_healthy
      mock-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres/ingestion_db
      - UPSTREAM_URL=http://mock-api:8000
      - PYTHONUNBUFFERED=1

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "${HOST_PORT_DASHBOARD:-8501}:8501"
    depends_on:
      - mock-api
      - ingestion-service
    environment:
      - MOCK_API_URL=http://mock-api:8000
      # Note: 'ingestion-service' matches the service name in compose
      - INGESTOR_URL=http://ingestion-service:8000
